kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: kindest/node:v1.26.6@sha256:6e2d8b28a5b601defe327b98bd1c2d1930b49e5d8c512e1895099e4504007adb
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 30001
    hostPort: 30001
    protocol: UDP
  - containerPort: 30002
    hostPort: 30002
    protocol: UDP
  - containerPort: 30003
    hostPort: 30003
    protocol: UDP
  - containerPort: 30004
    hostPort: 30004
    protocol: UDP
  - containerPort: 30005
    hostPort: 30005
    protocol: UDP