apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ts-operator
commonLabels:
  app: ts-operator
resources:
  - quake-operator-deployment.yaml
  - quake-operator-sa.yaml
  - quake-operator-service.yaml