apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mods.q3.magesgate.com
  annotations:
    creationTimestamp: null
spec:
  group: q3.magesgate.com
  versions:
    - additionalPrinterColumns:
        - jsonPath: ".spec.q3.mod"
          name: Mod
          type: string
      name: v1alpha
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          description: Schema for the Quake3 MODS API
          type: object
          properties:
            spec:
              type: object
              properties:
                datapacks:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      fileName:
                        type: string
                      destPath:
                        type: string
                      subPath:
                        type: string
                      isFolder:
                        type: boolean
                      uri:
                        type: string
                    required:
                      - fileName
                      - name
                      - uri
                args:
                  type: array
                  items:
                    type: string
            status:
              type: object
              default: { datapacks: []}
              required:
                - datapacks
              properties:
                datapacks:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      status:
                        type: string
                        default: New
                        enum: ["New", "Downloading", "Downloaded", "Failed"]
                      message:
                        type: string
                      job:
                        type: string
                        nullable: true
                        default: null
                    required:
                      - status
                  default: []
      subresources:
        status: {}
  scope: Namespaced
  names:
    plural: mods
    singular: mod
    kind: Mod